
export const metadata = {
    title: "Categories| My Ecommerce Website",
    description: "Generated by create next app",
};

import Products from "@/app/Component/Products";

export default function Page() {


    return (
        <>
            <Products />
        </>
    )
}
