
import React from 'react'

export const metadata = {
    title: "About Us | My Ecommerce Website",
    description: "Generated by create next app",
};

export default function page() {
    return (
        <div>
            <h2>aboutus</h2>
        </div>
    )
}
