
import React from 'react'

export const metadata = {
    title: "Contact Us | My Ecommerce Website",
    description: "Generated by create next app",
};

export default function page() {
    return (
        <div>

            <h1>contactus</h1>
        </div>
    )
}
